use_default_settings: true

server:
  secret_key: "a-long-random-secret-key-change-this-to-something-unique-1234567890"
  limiter: false
  image_proxy: true
  bind_address: "0.0.0.0"

search:
  safe_search: 0
  autocomplete: ""
  default_lang: ""
  formats:
    - html
    - json
